const LANGS = {
    es:{name:'Español',flag:'🇪🇸',welcome:'Bienvenido a CamaraEspia',no_cameras:'No hay camaras configuradas',settings:'⚙️ Ajustes',add_camera:'➕ Agregar camara',scan:'🔍 Buscar camaras',scanning:'Buscando camaras...',connecting:'Conectando...',connected:'Conectado',offline:'Sin conexion',live:'EN VIVO',photo:'Foto',record:'Grabar',stop:'Detener',servo:'Servo',settings_title:'Ajustes',language:'Idioma',theme:'Tema',dark:'Oscuro',light:'Claro',auto:'Auto',camera_name:'Nombre',wifi:'WiFi',battery:'Bateria',password:'Contraseña',enter_password:'Ingresa la contraseña de la camara',save:'Guardar',cancel:'Cancelar',back:'Volver',no_results:'Sin resultados',error:'Error'},
    en:{name:'English',flag:'🇺🇸',welcome:'Welcome to CamaraEspia',no_cameras:'No cameras configured',settings:'⚙️ Settings',add_camera:'➕ Add camera',scan:'🔍 Scan cameras',scanning:'Scanning...',connecting:'Connecting...',connected:'Connected',offline:'Offline',live:'LIVE',photo:'Photo',record:'Record',stop:'Stop',servo:'Servo',settings_title:'Settings',language:'Language',theme:'Theme',dark:'Dark',light:'Light',auto:'Auto',camera_name:'Name',wifi:'WiFi',battery:'Battery',password:'Password',enter_password:'Enter camera password',save:'Save',cancel:'Cancel',back:'Back',no_results:'No results',error:'Error'},
    pt:{name:'Português',flag:'🇧🇷',welcome:'Bem-vindo ao CamaraEspia',no_cameras:'Nenhuma camera configurada',settings:'⚙️ Configuracoes',add_camera:'➕ Adicionar camera',scan:'🔍 Buscar cameras',scanning:'Procurando...',connecting:'Conectando...',connected:'Conectado',offline:'Offline',live:'AO VIVO',photo:'Foto',record:'Gravar',stop:'Parar',servo:'Servo',settings_title:'Configuracoes',language:'Idioma',theme:'Tema',dark:'Escuro',light:'Claro',auto:'Auto',camera_name:'Nome',wifi:'WiFi',battery:'Bateria',password:'Senha',enter_password:'Digite a senha da camera',save:'Salvar',cancel:'Cancelar',back:'Voltar',no_results:'Sem resultados',error:'Erro'},
    fr:{name:'Français',flag:'🇫🇷',welcome:'Bienvenue sur CamaraEspia',no_cameras:'Aucune camera configuree',settings:'⚙️ Parametres',add_camera:'➕ Ajouter camera',scan:'🔍 Rechercher',scanning:'Recherche...',connecting:'Connexion...',connected:'Connecte',offline:'Hors ligne',live:'EN DIRECT',photo:'Photo',record:'Enregistrer',stop:'Arreter',servo:'Servo',settings_title:'Parametres',language:'Langue',theme:'Theme',dark:'Sombre',light:'Clair',auto:'Auto',camera_name:'Nom',wifi:'WiFi',battery:'Batterie',password:'Mot de passe',enter_password:'Entrez le mot de passe',save:'Enregistrer',cancel:'Annuler',back:'Retour',no_results:'Aucun resultat',error:'Erreur'},
    de:{name:'Deutsch',flag:'🇩🇪',welcome:'Willkommen bei CamaraEspia',no_cameras:'Keine Kameras konfiguriert',settings:'⚙️ Einstellungen',add_camera:'➕ Kamera hinzufuegen',scan:'🔍 Kameras suchen',scanning:'Suchen...',connecting:'Verbinden...',connected:'Verbunden',offline:'Offline',live:'LIVE',photo:'Foto',record:'Aufnehmen',stop:'Stopp',servo:'Servo',settings_title:'Einstellungen',language:'Sprache',theme:'Design',dark:'Dunkel',light:'Hell',auto:'Auto',camera_name:'Name',wifi:'WiFi',battery:'Akku',password:'Passwort',enter_password:'Kamera-Passwort eingeben',save:'Speichern',cancel:'Abbrechen',back:'Zurueck',no_results:'Keine Ergebnisse',error:'Fehler'},
    it:{name:'Italiano',flag:'🇮🇹',welcome:'Benvenuto in CamaraEspia',no_cameras:'Nessuna fotocamera configurata',settings:'⚙️ Impostazioni',add_camera:'➕ Aggiungi camera',scan:'🔍 Cerca camere',scanning:'Ricerca...',connecting:'Connessione...',connected:'Connesso',offline:'Offline',live:'DIRETTA',photo:'Foto',record:'Registra',stop:'Ferma',servo:'Servo',settings_title:'Impostazioni',language:'Lingua',theme:'Tema',dark:'Scuro',light:'Chiaro',auto:'Auto',camera_name:'Nome',wifi:'WiFi',battery:'Batteria',password:'Password',enter_password:'Inserisci password',save:'Salva',cancel:'Annulla',back:'Indietro',no_results:'Nessun risultato',error:'Errore'},
    ru:{name:'Русский',flag:'🇷🇺',welcome:'Добро пожаловать в CamaraEspia',no_cameras:'Нет настроенных камер',settings:'⚙️ Настройки',add_camera:'➕ Добавить камеру',scan:'🔍 Найти камеры',scanning:'Поиск...',connecting:'Подключение...',connected:'Подключено',offline:'Оффлайн',live:'ОНЛАЙН',photo:'Фото',record:'Запись',stop:'Стоп',servo:'Серво',settings_title:'Настройки',language:'Язык',theme:'Тема',dark:'Тёмная',light:'Светлая',auto:'Авто',camera_name:'Имя',wifi:'WiFi',battery:'Батарея',password:'Пароль',enter_password:'Введите пароль камеры',save:'Сохранить',cancel:'Отмена',back:'Назад',no_results:'Нет результатов',error:'Ошибка'},
    zh:{name:'中文',flag:'🇨🇳',welcome:'欢迎使用 CamaraEspia',no_cameras:'没有配置摄像头',settings:'⚙️ 设置',add_camera:'➕ 添加摄像头',scan:'🔍 搜索摄像头',scanning:'搜索中...',connecting:'连接中...',connected:'已连接',offline:'离线',live:'直播',photo:'拍照',record:'录像',stop:'停止',servo:'舵机',settings_title:'设置',language:'语言',theme:'主题',dark:'深色',light:'浅色',auto:'自动',camera_name:'名称',wifi:'WiFi',battery:'电池',password:'密码',enter_password:'输入摄像头密码',save:'保存',cancel:'取消',back:'返回',no_results:'无结果',error:'错误'},
    ja:{name:'日本語',flag:'🇯🇵',welcome:'CamaraEspiaへようこそ',no_cameras:'カメラが設定されていません',settings:'⚙️ 設定',add_camera:'➕ カメラ追加',scan:'🔍 カメラ検索',scanning:'検索中...',connecting:'接続中...',connected:'接続済み',offline:'オフライン',live:'ライブ',photo:'写真',record:'録画',stop:'停止',servo:'サーボ',settings_title:'設定',language:'言語',theme:'テーマ',dark:'ダーク',light:'ライト',auto:'自動',camera_name:'名前',wifi:'WiFi',battery:'バッテリー',password:'パスワード',enter_password:'カメラパスワードを入力',save:'保存',cancel:'キャンセル',back:'戻る',no_results:'結果なし',error:'エラー'},
    ko:{name:'한국어',flag:'🇰🇷',welcome:'CamaraEspia에 오신것을 환영합니다',no_cameras:'카메라가 설정되지 않았습니다',settings:'⚙️ 설정',add_camera:'➕ 카메라 추가',scan:'🔍 카메라 검색',scanning:'검색중...',connecting:'연결중...',connected:'연결됨',offline:'오프라인',live:'실시간',photo:'사진',record:'녹화',stop:'중지',servo:'서보',settings_title:'설정',language:'언어',theme:'테마',dark:'다크',light:'라이트',auto:'자동',camera_name:'이름',wifi:'WiFi',battery:'배터리',password:'비밀번호',enter_password:'카메라 비밀번호 입력',save:'저장',cancel:'취소',back:'뒤로',no_results:'결과 없음',error:'오류'},
    ar:{name:'العربية',flag:'🇸🇦',welcome:'مرحبا بكم في CamaraEspia',no_cameras:'لا توجد كاميرات',settings:'⚙️ الاعدادات',add_camera:'➕ اضافة كاميرا',scan:'🔍 بحث',scanning:'بحث...',connecting:'اتصال...',connected:'متصل',offline:'غير متصل',live:'مباشر',photo:'صورة',record:'تسجيل',stop:'ايقاف',servo:'سيرفو',settings_title:'الاعدادات',language:'اللغة',theme:'السمة',dark:'داكن',light:'فاتح',auto:'تلقائي',camera_name:'الاسم',wifi:'WiFi',battery:'البطارية',password:'كلمة المرور',enter_password:'ادخل كلمة مرور الكاميرا',save:'حفظ',cancel:'الغاء',back:'رجوع',no_results:'لا نتائج',error:'خطأ'},
    hi:{name:'हिन्दी',flag:'🇮🇳',welcome:'CamaraEspia में आपका स्वागत है',no_cameras:'कोई कैमरा कॉन्फ़िगर नहीं',settings:'⚙️ सेटिंग्स',add_camera:'➕ कैमरा जोड़ें',scan:'🔍 कैमरा खोजें',scanning:'खोज रहा है...',connecting:'कनेक्ट हो रहा है...',connected:'कनेक्टेड',offline:'ऑफलाइन',live:'लाइव',photo:'फ़ोटो',record:'रिकॉर्ड',stop:'रोकें',servo:'सर्वो',settings_title:'सेटिंग्स',language:'भाषा',theme:'थीम',dark:'डार्क',light:'लाइट',auto:'ऑटो',camera_name:'नाम',wifi:'WiFi',battery:'बैटरी',password:'पासवर्ड',enter_password:'कैमरा पासवर्ड दर्ज करें',save:'सहेजें',cancel:'रद्द करें',back:'वापस',no_results:'कोई परिणाम नहीं',error:'त्रुटि'},
    bn:{name:'বাংলা',flag:'🇧🇩',welcome:'CamaraEspia-তে স্বাগতম',no_cameras:'কোনো ক্যামেরা কনফিগার করা হয়নি',settings:'⚙️ সেটিংস',add_camera:'➕ ক্যামেরা যোগ',scan:'🔍 ক্যামেরা খুঁজুন',scanning:'খুঁজছে...',connecting:'সংযোগ...',connected:'সংযুক্ত',offline:'অফলাইন',live:'লাইভ',photo:'ছবি',record:'রেকর্ড',stop:'বন্ধ',servo:'সার্ভো',settings_title:'সেটিংস',language:'ভাষা',theme:'থিম',dark:'ডার্ক',light:'লাইট',auto:'অটো',camera_name:'নাম',wifi:'WiFi',battery:'ব্যাটারি',password:'পাসওয়ার্ড',enter_password:'ক্যামেরা পাসওয়ার্ড দিন',save:'সংরক্ষণ',cancel:'বাতিল',back:'পিছনে',no_results:'ফলাফল নেই',error:'ত্রুটি'},
    tr:{name:'Türkçe',flag:'🇹🇷',welcome:'CamaraEspia\'ya Hos Geldiniz',no_cameras:'Kamera yok',settings:'⚙️ Ayarlar',add_camera:'➕ Kamera ekle',scan:'🔍 Kamera ara',scanning:'Araniyor...',connecting:'Baglaniyor...',connected:'Bagli',offline:'Cevrimdisi',live:'CANLI',photo:'Foto',record:'Kaydet',stop:'Dur',servo:'Servo',settings_title:'Ayarlar',language:'Dil',theme:'Tema',dark:'Karanlik',light:'Acik',auto:'Oto',camera_name:'Ad',wifi:'WiFi',battery:'Pil',password:'Sifre',enter_password:'Kamera sifresini girin',save:'Kaydet',cancel:'Iptal',back:'Geri',no_results:'Sonuc yok',error:'Hata'},
    vi:{name:'Tiếng Việt',flag:'🇻🇳',welcome:'Chao mung den voi CamaraEspia',no_cameras:'Chua co camera nao',settings:'⚙️ Cai dat',add_camera:'➕ Them camera',scan:'🔍 Tim camera',scanning:'Dang tim...',connecting:'Dang ket noi...',connected:'Da ket noi',offline:'Mang offline',live:'TRUC TIEP',photo:'Anh',record:'Quay',stop:'Dung',servo:'Servo',settings_title:'Cai dat',language:'Ngon ngu',theme:'Chu de',dark:'Toi',light:'Sang',auto:'Tu dong',camera_name:'Ten',wifi:'WiFi',battery:'Pin',password:'Mat khau',enter_password:'Nhap mat khau camera',save:'Luu',cancel:'Huy',back:'Quay lai',no_results:'Khong co ket qua',error:'Loi'},
    th:{name:'ภาษาไทย',flag:'🇹🇭',welcome:'ยินดีต้อนรับสู่ CamaraEspia',no_cameras:'ยังไม่มีการตั้งค่ากล้อง',settings:'⚙️ การตั้งค่า',add_camera:'➕ เพิ่มกล้อง',scan:'🔍 ค้นหากล้อง',scanning:'กำลังค้นหา...',connecting:'กำลังเชื่อมต่อ...',connected:'เชื่อมต่อแล้ว',offline:'ออฟไลน์',live:'ถ่ายทอดสด',photo:'รูป',record:'บันทึก',stop:'หยุด',servo:'เซอร์โว',settings_title:'การตั้งค่า',language:'ภาษา',theme:'ธีม',dark:'มืด',light:'สว่าง',auto:'อัตโนมัติ',camera_name:'ชื่อ',wifi:'WiFi',battery:'แบตเตอรี่',password:'รหัสผ่าน',enter_password:'ป้อนรหัสผ่านกล้อง',save:'บันทึก',cancel:'ยกเลิก',back:'ย้อนกลับ',no_results:'ไม่มีผลลัพธ์',error:'ข้อผิดพลาด'},
    id:{name:'Indonesia',flag:'🇮🇩',welcome:'Selamat datang di CamaraEspia',no_cameras:'Belum ada kamera',settings:'⚙️ Pengaturan',add_camera:'➕ Tambah kamera',scan:'🔍 Cari kamera',scanning:'Mencari...',connecting:'Menghubungkan...',connected:'Tersambung',offline:'Offline',live:'LANGSUNG',photo:'Foto',record:'Rekam',stop:'Berhenti',servo:'Servo',settings_title:'Pengaturan',language:'Bahasa',theme:'Tema',dark:'Gelap',light:'Terang',auto:'Otomatis',camera_name:'Nama',wifi:'WiFi',battery:'Baterai',password:'Kata sandi',enter_password:'Masukkan kata sandi kamera',save:'Simpan',cancel:'Batal',back:'Kembali',no_results:'Tidak ada hasil',error:'Kesalahan'},
    pl:{name:'Polski',flag:'🇵🇱',welcome:'Witamy w CamaraEspia',no_cameras:'Brak kamer',settings:'⚙️ Ustawienia',add_camera:'➕ Dodaj kamera',scan:'🔍 Szukaj kamer',scanning:'Szukanie...',connecting:'Laczenie...',connected:'Polaczono',offline:'Offline',live:'NA ZYWO',photo:'Zdjecie',record:'Nagrywaj',stop:'Zatrzymaj',servo:'Servo',settings_title:'Ustawienia',language:'Jezyk',theme:'Motyw',dark:'Ciemny',light:'Jasny',auto:'Auto',camera_name:'Nazwa',wifi:'WiFi',battery:'Bateria',password:'Haslo',enter_password:'Wprowadz haslo kamery',save:'Zapisz',cancel:'Anuluj',back:'Wstecz',no_results:'Brak wynikow',error:'Blad'},
    uk:{name:'Українська',flag:'🇺🇦',welcome:'Ласкаво просимо до CamaraEspia',no_cameras:'Немає налаштованих камер',settings:'⚙️ Налаштування',add_camera:'➕ Додати камеру',scan:'🔍 Знайти камери',scanning:'Пошук...',connecting:'Підключення...',connected:'Підключено',offline:'Офлайн',live:'ОНЛАЙН',photo:'Фото',record:'Запис',stop:'Стоп',servo:'Серво',settings_title:'Налаштування',language:'Мова',theme:'Тема',dark:'Темна',light:'Світла',auto:'Авто',camera_name:"Iм'я",wifi:'WiFi',battery:'Батарея',password:'Пароль',enter_password:"Введiть пароль камери",save:'Зберегти',cancel:'Скасувати',back:'Назад',no_results:'Немає результатів',error:'Помилка'},
    ms:{name:'Melayu',flag:'🇲🇾',welcome:'Selamat datang ke CamaraEspia',no_cameras:'Tiada kamera dikonfigurasi',settings:'⚙️ Tetapan',add_camera:'➕ Tambah kamera',scan:'🔍 Cari kamera',scanning:'Mencari...',connecting:'Menyambung...',connected:'Bersambung',offline:'Offline',live:'LANGSUNG',photo:'Gambar',record:'Rakam',stop:'Henti',servo:'Servo',settings_title:'Tetapan',language:'Bahasa',theme:'Tema',dark:'Gelap',light:'Terang',auto:'Auto',camera_name:'Nama',wifi:'WiFi',battery:'Bateri',password:'Kata laluan',enter_password:'Masukkan kata laluan kamera',save:'Simpan',cancel:'Batal',back:'Kembali',no_results:'Tiada hasil',error:'Ralat'},
    sw:{name:'Kiswahili',flag:'🇰🇪',welcome:'Karibu CamaraEspia',no_cameras:'Hakuna kamera',settings:'⚙️ Mpangilio',add_camera:'➕ Ongeza kamera',scan:'🔍 Tafuta kamera',scanning:'Inatafuta...',connecting:'Inaunganisha...',connected:'Imeunganishwa',offline:'Nje ya mtandao',live:'MOJA KWA MOJA',photo:'Picha',record:'Rekodi',stop:'Simama',servo:'Servo',settings_title:'Mpangilio',language:'Lugha',theme:'Mandhari',dark:'Giza',light:'Nuru',auto:'Otomatiki',camera_name:'Jina',wifi:'WiFi',battery:'Betri',password:'Nenosiri',enter_password:'Weka nenosiri ya kamera',save:'Hifadhi',cancel:'Ghairi',back:'Rudi',no_results:'Hakuna matokeo',error:'Hitilafu'},
    tl:{name:'Filipino',flag:'🇵🇭',welcome:'Maligayang pagdating sa CamaraEspia',no_cameras:'Walang camera',settings:'⚙️ Settings',add_camera:'➕ Dagdag camera',scan:'🔍 Hanapin camera',scanning:'Hinahanap...',connecting:'Kumokonekta...',connected:'Nakakonekta',offline:'Offline',live:'LIVE',photo:'Foto',record:'I-record',stop:'Itigil',servo:'Servo',settings_title:'Settings',language:'Wika',theme:'Tema',dark:'Dilim',light:'Liwanag',auto:'Auto',camera_name:'Pangalan',wifi:'WiFi',battery:'Battery',password:'Password',enter_password:'Ilagay ang password ng camera',save:'I-save',cancel:'Kanselahin',back:'Bumalik',no_results:'Walang resulta',error:'Error'},
    nl:{name:'Nederlands',flag:'🇳🇱',welcome:'Welkom bij CamaraEspia',no_cameras:'Geen camera\'s geconfigureerd',settings:'⚙️ Instellingen',add_camera:'➕ Camera toevoegen',scan:'🔍 Zoek camera\'s',scanning:'Zoeken...',connecting:'Verbinden...',connected:'Verbonden',offline:'Offline',live:'LIVE',photo:'Foto',record:'Opnemen',stop:'Stop',servo:'Servo',settings_title:'Instellingen',language:'Taal',theme:'Thema',dark:'Donker',light:'Licht',auto:'Auto',camera_name:'Naam',wifi:'WiFi',battery:'Batterij',password:'Wachtwoord',enter_password:'Voer camera wachtwoord in',save:'Opslaan',cancel:'Annuleren',back:'Terug',no_results:'Geen resultaten',error:'Fout'}
};

let _lang = localStorage.getItem('lang') || 'es';
let T = LANGS[_lang];

function setLang(l) { _lang = l; T = LANGS[l]; localStorage.setItem('lang', l); document.documentElement.lang = l; }
function t(k) { return (T && T[k]) || (LANGS.en[k]) || k; }
function getLang() { return _lang; }
function getAllLangs() { return Object.keys(LANGS).map(k => ({id:k, name:LANGS[k].name, flag:LANGS[k].flag})); }
