# esp_check_pins.ps1 - Verificar asignacion de pines
# Este script es un placeholder para futuras verificaciones automatizadas
Write-Host "CamaraEspia-ESP32S3 - Verificacion de Pines" -ForegroundColor Cyan
Write-Host ""
Write-Host "Pines asignados:" -ForegroundColor Yellow
Write-Host "  GPIO0  -> Boton BOOT (pull-up)"
Write-Host "  GPIO1  -> PIR HC-SR501"
Write-Host "  GPIO2  -> Servo SG90 (LEDC)"
Write-Host "  GPIO3  -> Battery ADC (divisor 100k)"
Write-Host "  GPIO4  -> Camara SIOD (I2C)"
Write-Host "  GPIO5  -> Camara SIOC (I2C)"
Write-Host "  GPIO6  -> Camara VSYNC"
Write-Host "  GPIO7  -> Camara HREF"
Write-Host "  GPIO8  -> Camara D2"
Write-Host "  GPIO9  -> Camara D1"
Write-Host "  GPIO10 -> Camara D3"
Write-Host "  GPIO11 -> Camara D0"
Write-Host "  GPIO12 -> Camara D4"
Write-Host "  GPIO13 -> Camara PCLK"
Write-Host "  GPIO15 -> Camara XCLK"
Write-Host "  GPIO16 -> Camara D7"
Write-Host "  GPIO17 -> Camara D6"
Write-Host "  GPIO18 -> Camara D5"
Write-Host "  GPIO21 -> SD CS"
Write-Host "  GPIO40 -> SD MOSI"
Write-Host "  GPIO41 -> SD CLK"
Write-Host "  GPIO42 -> SD MISO"
Write-Host "  GPIO47 -> LED Estado"
Write-Host ""
Write-Host "Pines PROHIBIDOS:" -ForegroundColor Red
Write-Host "  GPIO19-20  -> USB"
Write-Host "  GPIO26-37  -> Octal Flash/PSRAM"
Write-Host "  GPIO43-44  -> UART0"
Write-Host "  GPIO45-46  -> Strapping"
