; CamaraEspia-ESP32S3 - PlatformIO Configuration
; Cámara de seguridad basada en ESP32-S3 N16R8

[env:esp32s3]
platform = espressif32@6.3.2
board = esp32-s3-n16r8
framework = arduino

; Particiones custom
board_build.partitions = partitions/custom_partitions.csv

; Build flags
build_flags =
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_SPEED_80M=1
    -DBOARD_HAS_CAM
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; Upload y monitor
upload_speed = 115200
upload_resetmode = usb-reset
monitor_speed = 115200
upload_port = auto

; Librerías
lib_deps =
    esp32-camera
    bblanchon/ArduinoJson@^7.0.0
    me-no-dev/ESPAsyncWebServer@^1.2.3

; Monitor filtra ruido
monitor_filters = esp32_exception_decoder
